Repository yalelibrary/yul-dc-blacklight, pull requests merged in 2020-08, with the labels that each got.

#222 Make the footer responsive
  app/assets/stylesheets/customOverrides/footer.scss
  app/assets/stylesheets/customOverrides/header.scss
  app/views/shared/_footer.html.erb
  spec/system/footer_spec.rb
Labels: Feature

#220 Add an aria label to search form
  app/views/catalog/_search_form.html.erb
Labels: Feature

#223 Fix header content height on condensed view
  app/views/shared/_header_navbar.html.erb
Labels: Bug

#226 Style facets with Yale aesthetic
  app/assets/images/x2x.png
  app/assets/stylesheets/customOverrides/main.scss
  app/controllers/catalog_controller.rb
  spec/system/view_facet_spec.rb
Labels: Feature

#229 Relocate tools and links to bottom of page
  app/views/catalog/_show_main_content.html.erb
  app/views/catalog/_show_sidebar.html.erb
Labels: Feature

#231 Reorder and add facets
  app/controllers/catalog_controller.rb
  spec/system/view_facet_spec.rb
Labels: Feature

#235 Facet styling
  app/assets/stylesheets/customOverrides/facets.scss
Labels: Feature

#237 Security fix for CVE-2020-7660
  package.json
  yarn.lock
Labels: dependencies

#238 Enable selection of UV settings
  app/assets/stylesheets/customOverrides/main.scss
  app/views/catalog/_show_main_content.html.erb
  app/views/catalog/_show_sidebar.html.erb
Labels: Bug

#241 Added the Blacklight Gallery view
  Gemfile
  Gemfile.lock
  app/assets/javascripts/blacklight_gallery.js
  app/assets/javascripts/openseadragon.js
  app/assets/stylesheets/blacklight_gallery.css.scss
  app/assets/stylesheets/openseadragon.css
  app/controllers/application_controller.rb
  app/controllers/catalog_controller.rb
  app/models/solr_document.rb
Labels: Feature

#243 Remove left and right page margin
  app/assets/stylesheets/customOverrides/footer.scss
  app/assets/stylesheets/customOverrides/header.scss
  app/assets/stylesheets/customOverrides/main.scss
Labels: Feature

#254 Added highlight fields on search matches
  app/controllers/catalog_controller.rb
  docs/MarcIndexer.html
  docs/VoyagerIndexingService.html
  spec/controllers/catalog_controller_spec.rb
  spec/helpers/citation_helper_spec.rb
  spec/support/solr_documents/metadata_cloud_with_visibility.rb
  spec/system/facet_by_year_spec.rb
  spec/system/highlight_in_search_spec.rb
  spec/system/search_fields_spec.rb
  spec/system/view_fields_in_display_spec.rb
  spec/system/view_fields_in_search_spec.rb
Labels: Feature

#256 Search term highlighting in title
  app/assets/stylesheets/customOverrides/search_result.scss
  app/views/catalog/_index_header.html.erb
  spec/system/highlight_in_search_spec.rb
  spec/system/sort_in_search_spec.rb
Labels: Feature
